GET http://localhost:3001
###

GET http://localhost:3001/login


### The below won't work because we;ve not defined the post method  for the endpoint 
POST http://localhost:3001

### But the below will work becuse we;ve defined the endpoint /register
POST  http://localhost:3001/register
Content-Type: application/json

{
    "username": "Davie",
    "password": "123@Signal10"
}

### DELETE Request
DELETE http://localhost:3001/users/15

### PUT Request
PUT http://localhost:3001/users/
Content-Type: application/json

[
    {
        "id": 15,
        "username": "Davie",
        "password": "123@Signal10" 
    }, 
    {
        "id": 30,
        "username": "Abudi",
        "password": "345Muleke@98"
    }
    
]

### PUT Request

PUT http://localhost:3001/users/
Content-Type: application/json

{
    "users":[
        {
            "id": 15,
            "username": "Davie",
            "password": "123@Signal10" 
        }, 
        {
            "id": 30,
            "username": "Abudi",
            "password": "345Muleke@98"
        }
        
    ] 
}

### PATCH Request
PATCH http://localhost:3001/users/12
Content-Type: application/json

{
    "username": "Anyuru"
}